import { ethers } from "ethers";
import { readFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// LOCAL USE ONLY: Anvil/Hardhat default account #0 private key. Never use on any live network.
const LOCAL_PRIVATE_KEY = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80";
const LOCAL_RPC_URL = "http://127.0.0.1:8545";

function loadArtifact(name: string) {
  const path = join(__dirname, "..", "artifacts", "contracts", `${name}.sol`, `${name}.json`);
  return JSON.parse(readFileSync(path, "utf-8"));
}

// Resolve deployed contract addresses from deployments/localhost/*.json (written by the deploy scripts).
function loadDeployedAddress(name: string): string {
  const file = join(__dirname, "..", "deployments", "localhost", `${name}.json`);
  try {
    return JSON.parse(readFileSync(file, "utf-8")).address;
  } catch {
    throw new Error(
      `No deployment found for ${name} at ${file}. Deploy the contracts first (scripts/deployDirect.ts).`,
    );
  }
}

async function main() {
  const provider = new ethers.JsonRpcProvider(LOCAL_RPC_URL);
  const signer = new ethers.Wallet(LOCAL_PRIVATE_KEY, provider);

  const nftAddress = loadDeployedAddress("AccessNFT");
  const nftArtifact = loadArtifact("AccessNFT");
  const nft = new ethers.Contract(nftAddress, nftArtifact.abi, signer);

  // The proof data generated by Semaphore
  const proof = {
    merkleTreeDepth: 1,
    merkleTreeRoot: "5971644768800692991947631472118425334028045883019724522721770548264953610582",
    nullifier: "14380812933768887131295643276977020379755876539891335886836834504769825251676",
    message: "30936211220281168307165930438217712725060455440826680500771308924404041252864",
    scope: "30936211220281168307165930438217712725060455440826680500771308924404041252864",
    points: [
      "17588551928713406608497454676038850387742115257143888745550223301097525202003",
      "20418168005002769227054543124170475135476501240948274997717654414006481222445",
      "21865773764491627596567122356191764423500642658852270227609108045954267443549",
      "14113339093983022193904132624989133590035002503358143181915470317907399415378",
      "2312907658006127537469757543470255769549815432179375405567310314806000759675",
      "11656923030638609862197034425947066869582181378258833321338166691665370687129",
      "17902863600419647452742885986644259828659126274115665461406887458773859238616",
      "4875054138594926217017167601854075859368843474022529835104291355594042909440",
    ],
  };

  console.log("Submitting ZK proof to mint NFT...");
  console.log("Nullifier:", proof.nullifier);

  try {
    // Call AccessNFT.mint() with the SemaphoreProof struct
    const tx = await nft.mint(proof);
    const receipt = await tx.wait();

    console.log("\n========================================");
    console.log("  NFT MINTED SUCCESSFULLY!");
    console.log("========================================");
    console.log("Transaction:", receipt.hash);
    console.log("Block:", receipt.blockNumber);
    console.log("Gas used:", receipt.gasUsed.toString());

    // Check who owns the NFT
    const nextId = await nft.nextTokenId();
    const tokenId = nextId - 1n;
    const owner = await nft.ownerOf(tokenId);
    console.log("Token ID:", tokenId.toString());
    console.log("Owner:", owner);
  } catch (e: any) {
    console.error("Mint failed:", e.shortMessage || e.message);
    if (e.data) console.error("Data:", e.data);
    if (e.reason) console.error("Reason:", e.reason);
  }
}

main().catch(err => {
  console.error("Failed:", err);
  process.exit(1);
});
